pstree: Linking with libintl.
Curently pstree does built, at least on ppc64le, because it does
not have a explicit link against gettext, causing the following error:

  peekfd.o: In function `print_version':
  peekfd.c:(.text+0x160): undefined reference to `libintl_gettext'
  peekfd.c:(.text+0x18c): undefined reference to `libintl_gettext'
  peekfd.c:(.text+0x1ac): undefined reference to `libintl_gettext'

peekfd depends on libint because of the following macro:

  #define _(String) gettext (String)